# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "docopt", "~> 0.6.1"

#gem "protobuf", "~> 3.10"

#gem "rbczmq", :git => "https://github.com/methodmissing/rbczmq.git", :branch => "master"

gem "ffi-rzmq", "~> 2.0"

gem "google-protobuf", "~> 3.9"
