requires 'IO::Socket::SSL', '2.0';
requires 'ZMQ::FFI', '1.17';
requires 'YAML', '1.29';
requires 'Google::ProtocolBuffers::Dynamic', '0.27';

on 'develop' => sub {
    recommends 'Perl::Tidy', '20200110';
};
