requires 'perl', '5.28.1';
requires 'Getopt::Long::Descriptive', '0.109';
requires 'Google::ProtocolBuffers::Dynamic', '0.31';
requires 'File::Find::Rule', '0.34';
requires 'JSON', '4.03';
requires 'YAML', '1.30';
requires 'ZMQ::FFI', '1.17';

on 'develop' => sub {
    recommends 'Perl::Tidy', '20210111';
};
