#!/usr/bin/env node

/*
 * -*- coding: utf-8 -*-
 *
 * jomiel-examples
 *
 * Copyright
 *  2019 Toni Gündoğdu
 *
 *
 * SPDX-License-Identifier: Apache-2.0
 */

'use strict';

process.env.NODE_PATH = '.';
require('module').Module._initPaths();

const cmdr = require('commander');

cmdr
  .usage('[options] <uri ...>')
  .option('-r, --router-endpoint <addr>',
    'Specify the router endpoint address',
    'tcp://localhost:5570')
  .option('-V, --version-zmq',
    'Display ZeroMQ version and exit')
  .option('-j, --output-json',
    'Print dumped messages in JSON')
  .option('-q, --be-terse',
    'Be brief and to the point; dump interesting details only');

cmdr.parse(process.argv);

if (cmdr.versionZmq) {
  const zmq = require('zeromq');
  console.log('ZeroMQ version %s', zmq.version);
  process.exit();
}

if (!cmdr.args.length) {
  console.error('error: input URI not given');
  process.exit(1);
}

const Jomiel = require('lib/jomiel').Jomiel;
const jomiel = Jomiel.create(cmdr);

jomiel.connect();

cmdr.args.forEach(uri => {
  jomiel.inquire(uri);
});

// vim: set ts=2 sw=2 tw=72 expandtab:
